### ISSUE TITLE
format of anno.refFlat

### ISSUE THREAD

**Issue by drejom** [guoweilong/cgmaptools#1]
Hi, 
Thanks for what looks like a great package. In the documentation for for the lollipop plot, you suggest the example

```
cgmaptools lollipop -i matrix.CG.gz -a anno.refFlat
```

But theres no information on how to use the -a flag or the format for `anno.refFlat.` Can you provide some more documentation on how you obtained the example lollipop plot?

Thanks,

**Comment by guoweilong** [comment]
Hi @drejom  ,

Thanks for your interest in CGmapTools.

Actually, "cgmaptools" is a wrapper for about 40 functions. You can try the command "cgmaptools lollipop -h" to get more details. For example, you can see the guidance here: [https://cgmaptools.github.io/cgmaptools_documentation/graphics.html#lollipop](https://cgmaptools.github.io/cgmaptools_documentation/graphics.html#lollipop) 

Thanks for your feedback. I just udpated the help information for the command "cgmaptools lollipop". Hope you can find it helpful.

Best,
Weilong

**Comment by drejom** [comment]
Great, thanks Weilong! I checked tried `cgmaptools lollipop -h` but it gives no details in the version I have (0.0.3). The updated documentation is very helpful!
Cheers
Den
