### ISSUE TITLE
Quenstion alignment for scBS-seq ?

### ISSUE THREAD

**Issue by hmyh1202** [guoweilong/cgmaptools#11]
Hi, WeiLong:

I have sequenced some single-cell bisulfite PE data, and aligned to reference using bismark.

In your related scBS-seq paper, you also used the unmapped single reads for mapping.

In my study, I had used the --non_directional for both PE mapping  and unmapped single reads mapping, and BAM files was merged by using samtools merge, and  followed by duplication by samtools in SE mode( -s and -S， for both PE and SE in the merged SAM file ). And bismark_methylation_extractor was used for mC calling.

So, was that rigth ? My quenstion is that Mr FuChou alway use that umapped single end reads for alignement, however if the PE and SE alignment results could result ambiguous mC.

Look  forward your reply！ And glad for your suggestion.

Thank you very much !

**Comment by Perry-Zhu** [comment]
Hi, @hmyh1202 

So late to reply.
Your pipeline for BS data mapping and deduplication is acceptable. 

Additional SE alignment of unmapped reads may rescue more data which is proposed based on the observed chimaeric DNA fragments in a BS-seq library. For details, you may refer to this post: 

> PBAT libraries may generate chimaeric read pairs
> https://sequencing.qcfail.com/articles/pbat-libraries-may-generate-chimaeric-read-pairs/
