### ISSUE TITLE
Use cgmaptools for bismark (paired end redas)

### ISSUE THREAD

**Issue by mrb20045** [guoweilong/cgmaptools#13]
Hi
How can I use cgmaptools for paired-end reads that aligned by bismark? At the moment cgmaptools don't support it.

Regards

**Comment by guoweilong** [comment]
You can try to call the DNA methylation using tools provided by Bismark. And then use "cgmaptools convert bismark2cgmap" to generate CGmap format file.
However, if you align reads with [BS-Seeker2](https://github.com/BSSeeker/BSseeker2), then you can feed the BAM to "cgmaptools convert bam2cgmap" directly.

Best,
Weilong Guo
