### ISSUE TITLE
Annotating DMR/DMS

### ISSUE THREAD

**Issue by harish0201** [guoweilong/cgmaptools#16]
Hi!

I've started using the toolkit and have found some DMRs and DMSs. As per the faq, you have mentioned I can intersect the outcomes using bedtools to annotate the genes.

Do I need to merge the DMR windows or DMS over a window and then annotate with the bed file?

Any suggestion is appreciated!

**Comment by guoweilong** [comment]
I guess you need. The regions predicted by **cgmaptools dm**r might be very close. You may want to extend them to some distances and try to see if they can be merged as a large one.

While, if you are looking for the **bedtools** intersect region, and then unique these regions/merged these regions for counting, it may be a similar way.

Best,
Weilong

**Comment by harish0201** [comment]
Alright, will try that and get back to you. Thanks for the software! It runs very fast!

**Comment by hmyh1202** [comment]
cool

Another question for DMS and DMR analysis：
how to do DMS or DMR using more than two sample: such as  sam1 and sam2 versus sam3 and sam4.

**Comment by guoweilong** [comment]
You can try to merge two CGmap files into one.
Following commands may help:
**_cgmaptools merge2 cgmap_** # for merging two CGmap files to one CGmap file
**_cgmaptools mergelist tosingle_** # for merging multiple CGmap files into one CGmap file.

Best,
Weilong
