### ISSUE TITLE
How to interpret a cgmaptool DMR file

### ISSUE THREAD

**Issue by AntonioGPS** [guoweilong/cgmaptools#17]
I run Bismark, and then cgmaptool to look for DMR between two conditions
I got a DMR file after intersecting two files obtained after using cgmaptools, but I do not fully understand or know how to interpret such a DMR file 

e.g. This first column is part of the final  DMR file (used in a CG context)
Fvb1	1638	1695	58	-1.4065	1.90e-01	0,9483	1	0,9483	6
I understand the under condition 1, 94,83% of the 6 CG are methylated, whereas 100% are methylated under condition 2. 

If that is true, how and why this is recognized as a DMR?. Should I apply a p-value filtering ?

![image](https://user-images.githubusercontent.com/5872859/54985028-5b882c00-4fb0-11e9-869d-2cda8520da52.png)

**Comment by guoweilong** [comment]
@AntonioGPS Thanks for your quesiton.

Actually, the report contains all the Dynamic Fragmented Regions been evaluated, and not all the reported regions are DMR. I would use a script to adjsust p-value to FDRs, and then selected regions  that are FDR<0.05.

Best,
Weilong Guo

**Comment by harish0201** [comment]
Hi, 

I have similar question. Should we be also filtering on the basis of the methylation difference? That is, say should MethB-MethA be > 10% or more etc?

**Comment by guoweilong** [comment]
I suggest to consider both "delta methylation level" and "p-values".
"delta methylation level" should consider two side: |MethA-MethB| > 10%

Best,
Weilong
