### ISSUE TITLE
Problem with CGmapMethInBins

### ISSUE THREAD

**Issue by doncarlos999** [guoweilong/cgmaptools#22]
Hi, 
Thanks for the great set of tools but I am having an issue with CGmapMethInBins.

My CGmap file looks like this:
```
chr1    C       10004   CHH     CC      0.0     0       1
chr1    C       10005   CHH     CC      0.0     0       1
```
However when I run the command :
`cgmaptools mbin -i head_chr1.CGmap.txt -c 1 -B 25 > 25bin.tsv`

The output has na where there should be 0 as in the CGmap above:
`chr1    10001   10025   na`

Also the resultant file does not even cover all of the positions in the input file.
`tail -n 5 head_chr1.CGmap`
```
chr1    C       264050  CHG     CA      0.0     0       1
chr1    C       264057  CHH     CA      0.0     0       1
chr1    C       264059  CHH     CA      0.0     0       1
chr1    C       264061  CHH     CA      0.0     0       1
chr1    C       264078  CHH     CA      0.0     0       1
```
`tail -n 5 25bin.tsv`
```
chr1    121301  121325  na
chr1    121326  121350  na
chr1    121351  121375  na
chr1    121376  121400  na
chr1    121401  121425  na
```
This cropping is even worse when using context specific mbin.
`cgmaptools mbin -i head_chr1.CGmap.txt -c 1 -B 25 -C CG > 25CGbin.tsv`
`tail -n 5 25CGbin.tsv`
```
chr1    13676   13700   na
chr1    13701   13725   na
chr1    13726   13750   na
chr1    13751   13775   na
chr1    13776   13800   na
```
                                                        
cgmaptools Version:  0.1.2                                                                                                                 
I have tried with python 2.6.9 and python 3.7.2 and the problem appears in both.
I have attached the sample of my CGmap file that I used in the above examples
Any help with this would be greatly appreciated.

[head_chr1.CGmap.txt](https://github.com/guoweilong/cgmaptools/files/3119369/head_chr1.CGmap.txt)

**Comment by guoweilong** [comment]
Hi @doncarlos999 ,

Thanks for your feedback. It seems to be a bug in code. And we just update the source code for this program.
Can you update the source code from https://github.com/guoweilong/cgmaptools/blob/master/src/CGmapMethInBins.py
for your local version, and see if the output is improved to right version?

We'll formally release the updated version if it runs well on your data set. And looking forward for your feedback.

Best,
Weilong

**Comment by doncarlos999** [comment]
Hi @guoweilong ,
Thanks so much for helping with this and for your quick response.

The updated source code has fixed the truncation problem but all but the last line are na.

```
➜  25bp_bdg  19-04-29 10:02 wc -l 25bin.tsv            
10564 25bin.tsv
➜  25bp_bdg  19-04-29 10:02 grep na 25bin.tsv | wc -l 
10563
➜  25bp_bdg  19-04-29 10:02 tail -n 4 25bin.tsv      
chr1    264001  264025  na
chr1    264026  264050  na
chr1    264051  264075  na
chr1    264076  264100  0.0473

```
```
➜  25bp_bdg  19-04-29 10:01 wc -l 25CGbin.tsv       
10560 25CGbin.tsv
➜  25bp_bdg  19-04-29 10:01 grep na 25CGbin.tsv | wc -l
10559
➜  25bp_bdg  19-04-29 10:01 tail -n 4 25CGbin.tsv      
chr1    263901  263925  na
chr1    263926  263950  na
chr1    263951  263975  na
chr1    263976  264000  0.3076
```

**Comment by guoweilong** [comment]
Hi @doncarlos999 ,

This function will scan from 1st base to the last base.
Thus, some region without enough coverage, will output "NA".
From my side, all the last lines are NOT "NA". So is this what you mean?

Best,
Weilong

**Comment by doncarlos999** [comment]
Did you try to run it on the file I attached in my first post?
If so can you attach the results with the same command that I am running?
`cgmaptools mbin -i head_chr1.CGmap.txt -c 1 -B 25 -C CG > 25CGbin.tsv`

I set the coverage to minimum 1 base. You can see in this file that there are many bases with more than 1 coverage but they are not being picked up in the scan.

Thanks
Carl

**Comment by guoweilong** [comment]
Hi Carl,

I just modified the code again, and commit the changes to github. Could you see if the new code works well for your data?

Looking forward to your feedback!

Best,
Weilong

**Comment by doncarlos999** [comment]
Hi @guoweilong 

This has solved the issue. It now outputs the correct bins.

Thanks a lot for the assistance
