### ISSUE TITLE
methylation effective coverage (mec) figure 

### ISSUE THREAD

**Issue by Surajuvm** [guoweilong/cgmaptools#23]
Hello Weilong,

I have been using cgmaptools to analyze my wgbs reads following bsseeker2 pipeline. I ran into a hiccup while determining coverage in the CGmap file. 

I used the following code:
```
cgmaptools mec stat -i ~/scratch/Align/MethCalls/CGmap/1117IL.fm.sort.rmdup.bam.CGmap.gz.CGmap -p 1117IL -f png > 1117IL.mec_stat.data
```
The code ran to completion and I get the 1117IL.mec_stat.data file; however, it did not produce figures. I received following error message

```
ValueError: Image size of 1100x140976 pixels is too large. It must be less than 2^16 in each direction.
```
It seems like the default value of pixel is too large; is there an easy fix to this problem? I would prefer to have those figures depicting methylation coverage. 

Thank you,
Suraj

**Comment by guoweilong** [comment]
How many chromosomes/scaffolds do you have in your input file? This part code will dynamically adjust the range of figure by the number of chromosomes.

Best,
Weilong

**Comment by Surajuvm** [comment]
There are 32 scaffolds/ chromosomes in the input file.

**Comment by Surajuvm** [comment]
I could get the cgmaptools mec bin to work for the same files.

**Comment by guoweilong** [comment]
Yes, you can try to plot it using these data.

**Comment by Surajuvm** [comment]
I don't understand what you are saying. I am not able to get the cgmaptools mec stat code to produce figures. However, I could get cgmaptools mec bin to produce figures for the same file. 
Like I said earlier the error says 
```
ValueError: Image size of 1100x140976 pixels is too large. It must be less than 2^16 in each direction.
```
Is there a way to fix this error and get the cgmaptools mec stat to produce figures?

**Comment by guoweilong** [comment]
I see. I thought you have found the way to draw figure using the output tables.

Maybe you can try to modify the file "./src/CGmapStatMeth.py"
line 238:
        plt.figure(figsize=(fW, fH*0.8))
to
        plt.figure(figsize=(fW, fH*0.2))

or to even smaller number, then the image size may not be too large.

Best,
Weilong

**Comment by Surajuvm** [comment]
Thank you Weilong. I got it to work :)
