### ISSUE TITLE
combining two strands for CpGs

### ISSUE THREAD

**Issue by benbfly** [guoweilong/cgmaptools#24]
Hi.  Typically the Watson strand C and Crick strand C will be listed separately in the CGmap file.  But I prefer to combine them into a single position (by summing the read counts) for visualization in the genome browser.  Does cgmaptools have a way to do this?  The most intuitive place would be in the cgmap2wig function, but I don't think it supports that.  Is there a way to do it?
Thanks! Ben.

**Comment by guoweilong** [comment]
Hi Ben,

CGmap file does not directly support your idea.
But you can try to write a script by reading the CGmap file, and check if two succeeded positions are CG context. Then output the file in the way you needed.

Best,
Weilong Guo

**Comment by benbfly** [comment]
thanks for the quick response.  Ok, the logic is pretty easy, i just wanted to make sure i wasn't duplicating something that was already there.  Thanks !

**Comment by benbfly** [comment]
I don’t know if you saw, but I added a script to do this.  It is in a pull request to you ..
