### ISSUE TITLE
mergelist tomatrix

### ISSUE THREAD

**Issue by kscott94** [guoweilong/cgmaptools#27]
#command:
cgmaptools mergelist tomatrix -i index -f TS559exoS.CGmap,TS559statS.CGmap -t exoS,statS -o TS559_mC_map -c 20

#head of index file:
TS559_Genomic_Sequence	6
TS559_Genomic_Sequence	7
TS559_Genomic_Sequence	9
TS559_Genomic_Sequence	12
TS559_Genomic_Sequence	14
TS559_Genomic_Sequence	18
TS559_Genomic_Sequence	21
TS559_Genomic_Sequence	26
TS559_Genomic_Sequence	27
TS559_Genomic_Sequence	40

error message:

File "/installs/cgmaptools-master/bin/CGmapFillIndex", line 119
    print "\t".join( [pos] + Site[pos] )
                 ^
SyntaxError: invalid syntax

#i've also tried gzipping the index and CGmaps files

**Comment by kscott94** [comment]
It is hard to tell, but the index is tab separated.

**Comment by guoweilong** [comment]
Are you using python2 or python3?
Currently, CGmapTools is only been tested in python2. You can try to use python2 for running the script to see if the code runs correctly.

Weilong
