### ISSUE TITLE
ASM C depth

### ISSUE THREAD

**Issue by dgroot** [guoweilong/cgmaptools#29]
When running ASM, you can set the C depth as a command line option.

In the code for ASM.pl, when the number is set to 0, there is an error message on line 126 that says "Error: Minimum read depth for C site to call methylation level when calling asr should be no less than 1".

However, if you actually set the option to 0 on the command line, then on line 110, there is an assignment operator that will automatically re-set to the default value of 3 (since the value of "0" is read as "FALSE", it will over-write the value).

The script does not tell you that it does this, and the error message is never printed. So the output is the same as if the default was set to 3, but it does not warn you about this!

I believe the same issue will happen when setting any of the parameters to 0, since the operator "||=" will always read the left hand side as "FALSE".

The operators should be changed to only set default values when the parameters have not been specified on the command line.

**Comment by perry-pz** [comment]
@dgroot Very good suggestion!

You are correct about the assignment of '0' to parameters and will be reassigned to the default values. We should avoid this type of coding. However, so far, it does not have any effects on the analysis as all the parameters in 'asm' function should not be assigned with a '0' value. Nevertheless, thanks for your very helpful suggestion!

Ping
