### ISSUE TITLE
tanghulu

### ISSUE THREAD

**Issue by Grace-0114** [guoweilong/cgmaptools#30]
Hi，Weilong.

I want to draw a picture like Fig2.D&E in your article, CGmapTools improves the precision of heterozygous SNV calls and supports allele-specific methylation detection and visualization in bisulfite-sequencing data.
I couldn't find your related any information about tanghulu of several samples’ ASM from your website or your paper. Please give me your associative code or information about Fig2.D&E in your article.
Thanks very much. 
I am looking forward to your reply.

Grace

**Comment by perry-pz** [comment]
Grace, we provide details about the utilities and usage at the homepage of [CGmapTools](https://cgmaptools.github.io). For tanghulu plot, you should refer to `https://cgmaptools.github.io/cgmaptools_documentation/graphics.html#tanghulu`

Ping

**Comment by Grace-0114** [comment]
I saw the parameter of cgmaptools tanghulu,but I didn't find any information about Graphics of several samples Fig.D or Fig.E of your paper in your website.


I just did this picture fig1 from my data.But I can't draw it like your picture. Your picture,fig2D in your paper is used with PS or AI software?
 

fig1 from my data
 

fig2D in your paper


Thanks very much for your reply.


Grace


------------------ 原始邮件 ------------------
发件人:&nbsp;"Guo"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月18日(星期三) 下午5:24
收件人:&nbsp;"guoweilong/cgmaptools"<cgmaptools@noreply.github.com&gt;;
抄送:&nbsp;"Grace"<415251493@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [guoweilong/cgmaptools] tanghulu (#30)




Grace, we provide details about the utilities and usage at the homepage of CGmapTools. For tanghulu plot, you should refer to https://cgmaptools.github.io/cgmaptools_documentation/graphics.html#tanghulu
 
Ping

**Comment by Perry-Zhu** [comment]
@Grace-0114 you are right. CGmapTools visualize the data by tanghulu. But the final presentation of your data should be further modified by AI or other similar tools if you need the display in our paper. For example, the SNP database annotation is not generated automatically by CGmapTools, I would prefer using IGV to output the svg format figure containing any annotations of the genome and then integrate into the tanghulu plots.

Best!

Ping

**Comment by Grace-0114** [comment]
Oh~Thanks very much for your patient explanation.

Best wishes.
Grace
