### ISSUE TITLE
Can you tell me how this become 6 CpG site? Seems logic error!!!

### ISSUE THREAD

**Issue by demis001** [guoweilong/cgmaptools#34]
DMR out file:

`1	13216	13303	-4.0234	2.43e-03	0.7300	0.9733	6`

Intersect file:

```
1	C	13216	CG	CG	0.62	5	8	0.90	9	10
1	G	13217	CG	CG	1.00	5	5	1.00	4	4
1	C	13283	CG	CG	0.76	13	17	1.00	21	21
1	G	13284	CG	CG	0.70	7	10	1.00	10	10
1	C	13302	CG	CG	0.63	12	19	1.00	22	22
1	G	13303	CG	CG	0.67	10	15	0.94	17	18
```

This looks 3 CG site to me? Any idea, how the number DMR number generated?

**Comment by guoweilong** [comment]
Hi @demis001 ,

CGmapTools and CGmap files will distinguish the strands for a CpG dinucleotide. Thus for one CpG dinucleotide, there will be two CG sites at different strands.

Best,
Weilong

**Comment by demis001** [comment]
Thanks! One more question, You menationed DMR will be filter based on t-test p value <0.01 and change mC >=0.1, Does this mean only hyper methylation only? I thought we have to do <= -0.1 to get hypo methyaltion.  It looks like the methylation ratio doesn't add up for specific DMR, I don't even know the direction. How you distinguish hyper and hypo methylation.  I have two samples passed to interesect -1 control and -2 treatment. I tried to figure out based on the methylation ratio from the DMR file, it doesn't add up  based on the given DMR.

**Comment by guoweilong** [comment]
Hi @demis001 ,

|delta mC| >=0.1 is for both directions. delta mC >=0.1 is for hyper-methylation, and delta<=-0.1 is for hypomethylation.

The raw output of "cgmaptools dmr" give you all the regions without any filtering. You need to/can filter them with your standards.

Best,
Weilong
