### ISSUE TITLE
CPP executables return exit-code 1 on help - they should return 0

### ISSUE THREAD

**Issue by Darkless012** [guoweilong/cgmaptools#36]
All C-build executable returns exit(0) on printing help.
All CPP executables (`ATCGmapMerge CGmapSelectByRegion CGmapMethInBed CGmapMethInFragReg`) should return exit(0) as well, since calling it does what it should (print help) and then exits correctly.
This is especially helpful for testing if commands are on PATH and runs "correctly" thus exit(1) could mean another errors.

**Comment by guoweilong** [comment]
Thanks for noticing me with this issue. The code is just modified and updated.

Best,
Weilong
