### ISSUE TITLE
Issue of using SNV calling tool

### ISSUE THREAD

**Issue by yu-ling-chang** [guoweilong/cgmaptools#42]
Hi,

I try to run the line "cgmaptools snv -i RR.ATCGmap.gz -m bayes -v bayes.vcf -o bayes.snv --bayes-dynamicP",
and I got an error "TypeError: unsupported operand type(s) for +: 'zip' and 'zip'"
Can you please give me guildance on how to fix it? 

Thanks,
Alice

**Comment by guoweilong** [comment]
For this issue, "cgmaptools cnv -i" does not support reading from gzip file directly. But you can run it using the following way:



zcat RR.ATCGmap.gz | cgmaptools snv -m bayes -v bayes.vcf -o bayes.snv --bayes-dynamicP




Best,
Weilong Guo



At 2020-10-29 07:56:58, "yu-ling-chang" <notifications@github.com> wrote:

Hi,

I try to run the line "cgmaptools snv -i RR.ATCGmap.gz -m bayes -v bayes.vcf -o bayes.snv --bayes-dynamicP",
and I got an error "TypeError: unsupported operand type(s) for +: 'zip' and 'zip'"
Can you please give me guildance on how to fix it?

Thanks,
Alice

**Comment by yu-ling-chang** [comment]
Hi Weilong,

It works!

Thank you so much.
Alice

**Comment by yu-ling-chang** [comment]
Hi Weilong,

I figured that even it ran though, the output file was empty. 

Then, I went to check for the error "TypeError: unsupported operand type(s) for +: 'zip' and 'zip'". This seems to be an issue of python2-->python3.
It seems to work if I change the line from:
[Prob, geno] = max(zip(pstP, ClearSet) + zip(V_pstP, VagueSet) )
to:
[Prob, geno] = max(list(zip(pstP, ClearSet)) + list(zip(V_pstP, VagueSet)) )

Please let me know if this is a correct change.

Thanks,
Alice

**Comment by guoweilong** [comment]
Thanks.


CGmapTools was developed under python 2. We'll try to update it to fit with python 3 in the future.



Best,
Weilong Guo



At 2020-10-30 01:06:34, "Alice" <notifications@github.com> wrote:

Hi Weilong,

I figured that even it ran though, the output file was empty.

Then, I went to check for the error "TypeError: unsupported operand type(s) for +: 'zip' and 'zip'". This seems to be an issue of python2-->python3.
It seems to work if I change the line from:
[Prob, geno] = max(zip(pstP, ClearSet) + zip(V_pstP, VagueSet) )
to:
[Prob, geno] = max(list(zip(pstP, ClearSet)) + list(zip(V_pstP, VagueSet)) )

Please let me know if this is a correct change.

Thanks,
Alice
