### ISSUE TITLE
bam2cgmap memory usage

### ISSUE THREAD

**Issue by sf-nevermore** [guoweilong/cgmaptools#5]
Hi,

I run the tool to convert the BSSeeker2 produced bam to cgmap. It used all the memory of my machine (64GB) and cannot proceed generating truncated output. 

"gzip: WGBS.CGmap.gz: unexpected end of file"

bam file size is 14G, ~380 million records. Does the tool demands lot of memory?

Thanks,
Hanbin

**Comment by guoweilong** [comment]
Hi Hanbin,


As your bam file is large, the processing would demand large memory for processing the pileup.


For your case, you can split your bam by chromosomes, and then run 'cgmaptools convert bam2cgmap' for each chromosome. In this way, you can speed up calling mC by running in parallel, and also save memory.


Best,
Weilong


At 2017-12-15 18:23:26, "Hanbin" <notifications@github.com> wrote:


Hi,

I run the tool to convert the BSSeeker2 produced bam to cgmap. It used all the memory of my machine (64GB) and cannot proceed generating truncated output.

"gzip: WGBS.CGmap.gz: unexpected end of file"

bam file size is 14G, ~380 million records. Does the tool demands lot of memory?

Thanks,
Hanbin

**Comment by sf-nevermore** [comment]
Hi Weilong,

I splited the bam by chromosomes, but it still takes up all the memory for converting a single chromosome. So I split the bam by 50M chunks using samtools region option. 
After I converted them to a list of CGmap.gz files, I assume that they can be simply concatenated into one single CGmap (cat cgmap* > out), without using the mergelist tool. Since they are non-overlapping chunks. Is it correct?

Best,
Hanbin

**Comment by guoweilong** [comment]
It might be correct, as the only thing I can expect is that you would lost some reads on the 50M boundary.

May I know how large is your memory? And how much would it costs the memory if splitting the bam files into chr?

Best,
Weilong

**Comment by sf-nevermore** [comment]
64GB RAM. I am never able to host a whole chr bam data into the memory. 50M length of the chromosome  typically takes 50% of the memory. So I can barely run 2 in parallel.

Hanbin

**Comment by guoweilong** [comment]
Thanks.  Generally, 64G is small for processing now.

And how large is  your genome? 

Are you feeding in all the chromosome sequence as fasta file for `cgmaptools convert bam2cgmap`? If   so, you may want to try to only feed in the corresponding chromosome, and that would expect to have lower cost of memory.

Best,
Weilong

**Comment by justinjohns** [comment]
Potentially a related issue. I have `Bismark`  BAM files, sorted with samtools. Have also tried on unsorted BAM files, and BAM files from the `filter_non_conversion` of `Bismark`.

If I run `cgmaptools convert bam2cgmap -b 0001.bam -g /shafer2/lynx/iberian/ena.fasta --rmOverlap -o 0001` I get the attached error:
*** Error in `/home/shafer/cgmaptools/bin/CGmapFromBAM': free(): invalid next size (fast): 0x00000000019e3a30 ***
[FULL ERROR] [error.txt](https://github.com/guoweilong/cgmaptools/files/1649367/error.txt)

This makes me think it's a memory issue but not sure how to debug. Computer has 256 GB of RAM, dual xeon. Sorted BAM is only 114 MB, genome is 2.5 GB, head and tail of BAM is here [50,000 lines]: 

[head_bam.txt](https://github.com/guoweilong/cgmaptools/files/1649368/head_bam.txt)
[tail_bam.txt](https://github.com/guoweilong/cgmaptools/files/1649369/tail_bam.txt)

Re-running alignment with BS2 to see if that helps. Thanks for any tips, been running scripts for maybe 10 hours so maybe the computer is just tired..

Justin

**Comment by guoweilong** [comment]
Hi Justin,


I have just updated the "cgmaptools convert bam2cgmap" function, by optimizing the usage of memory. I suggest you try the v0.0.9 (need to rebuild the code, by run install.sh).


Looking forwards to your feedback.


Best,
--
Weilong



At 2018-01-21 07:05:31, "justinjohns" <notifications@github.com> wrote:


Potentially a related issue. I have Bismark BAM files, sorted with samtools. Have also tried on unsorted BAM files, and BAM files from the filter_non_conversion of Bismark.

If I run cgmaptools convert bam2cgmap -b 0001.bam -g /shafer2/lynx/iberian/ena.fasta --rmOverlap -o 0001 I get the attached error:
*** Error in `/home/shafer/cgmaptools/bin/CGmapFromBAM': free(): invalid next size (fast): 0x00000000019e3a30 ***
[FULL ERROR] error.txt

This makes me think it's a memory issue but not sure how to debug. Computer has 256 GB of RAM, dual xeon. Sorted BAM is only 114 MB, genome is 2.5 GB, head and tail of BAM is here [50,000 lines]:

head_bam.txt
tail_bam.txt

Re-running alignment with BS2 to see if that helps. Thanks for any tips, been running scripts for maybe 10 hours so maybe the computer is just tired..

Justin

**Comment by justinjohns** [comment]
Hmm, perhaps it is an issue with my genome, because it is just made of several thousand scaffolds and not distinct chromosomes? (head below) 

`>ENA|LT174730|LT174730.1 Lynx pardinus genome assembly, scaffold: lp23s00001 ` 

Same error, new version - tried it on 2 computers as well: 

[error.txt](https://github.com/guoweilong/cgmaptools/files/1653612/error.txt)

`shafer@shafer:/shafer3/lynx_meth/analysis/cgmap$ cgmaptools -h
Program : cgmaptools (Tools for analysis in CGmap/ATCGmap format)
Version:  0.0.9`

Will try and re-run with cat genome and see.

**Comment by justinjohns** [comment]
Only seems to be an issue if --rmOverlap is added, otherwise bam2cgmap works fine. 

error: [rmOverlap.txt](https://github.com/guoweilong/cgmaptools/files/1661680/rmOverlap.txt)

**Comment by guoweilong** [comment]
We have updated the function in version v0.1.0. And you may want to try "--rmOverlap" with low memory cost.
We are looking forward to your feedback!

Best,
Weilong

**Comment by Grace-0114** [comment]
Hi,Weilong.

1. I have same issue about cgmaptools version 0.1.2.  
$cgmaptools convert bam2cgmap --rmOverlap -b AA09_bismark_sort.bam -g /genomeRef/MMUL.fa -o AA_09
My Bismark_sort  file by samtools: 40G  BAM.  Genome: 2.7 GB.
HPC, 1 node, thread 2, 50G memory.
How can I soft this problam?

2.$cgmaptools convert bismark2cgmap -i bismark.dat -o output.CGmap
Which file do I select as bismark.dat?
I have finished  programs in bismark version 0.20.0. 

Best.
Grace

**Comment by guoweilong** [comment]
Just notice this msg. Sorry for the late reply.

For your case, chose the 2nd way is faster. You can find one of the Bismark output in format such as following:

chr10   3107007 -       6       3       CG     CGT
chr10   3107024 -       9       3       CHH    CTT

Then use this one.

For the "cgmaptools convert bam2cgmap", it seems using "--rm-Overlap" parameter will require large memory (failed to release allocated memory). I'm trying to fix this problem.

Best,
Weilong
