### ISSUE TITLE
SNV calling result

### ISSUE THREAD

**Issue by 3211895** [guoweilong/cgmaptools#6]
Hi:
I've got some VCF files from the SNV calling. However, no genotype is 0/0. Is it a correct result?
Thanks

**Comment by guoweilong** [comment]
Thanks for your feedback. It is a bug, and has just been fixed.

You can download the newest version by clone from github.

We'll draw a new release later.

Thanks and best,

Weilong

**Comment by 3211895** [comment]
Hi:
Thank you. I still have a question about how to convert bam 2 cgmap.  Is the input file genome.fa the fastq of each individuals or the ref fastq? When I used the fastq of individuals,  it does not work.
[fai_build_core] different line length in sequence '(null)'.
Thanks 
Best

**Comment by guoweilong** [comment]
Hi,

Are you using Fastq as input or using Fasta as input?
the genome.fa are refenrece sequence information stored in fasta format.

Best,
Weilong

**Comment by 3211895** [comment]
Hi

I've used the latest version to perform SNV calling, however, all the genotypes are still 0/1, 1/1, 1/2 but no 0/0. Can I treat the SNV which does not exist in the VCF file as 0/0?
By the way, can I use the ATCGmap which is derived from BS seeker 2 directly to perform SNV calling?
Thank you
Best

**Comment by guoweilong** [comment]
@3211895 Hi, sorry for not making it clear.
We updated codes, but not made the new release. But you might still using the old release.
Now, you can try the new release today [v0.0.7](https://github.com/guoweilong/cgmaptools/releases) for this udpate.

Best,
Weilong

**Comment by 3211895** [comment]
@guoweilong Sorry for disturbing you again, however I've used the v0.0.7 version to call SNV, and derived the completely same result as the old version. I've found that the code of v0.0.7 version contained
 if ALT == "." :
 GT  = "0/0"
so I am not sure the reason. So can I  treat the SNV which does not exist in the VCF file as 0/0? 
Thank you very much

**Comment by guoweilong** [comment]
Hi,

If ALT == "." : 
  GT = "0/0"

The code indicates this site is covered and detetable, and same genotype with reference genome.

If you find a site in not exist in output VCF by CGmapTools, it indicates the sites are not detectable (not enough coverage for calculating a genotype). You can it make is as "./.".

Best,
Weilong

**Comment by 3211895** [comment]
@guoweilong Hi,
I am sorry, I means I can still not derive any SNP which genotype is 0/0, including the test dataset. Here is the VCF I derived from the test data:
##fileformat=VCFv4.2
##fileDate=20171221
##source=CGmapTools
##INFO=<ID=NS,Number=1,Type=Integer,Description="Number of Samples With Data">
##INFO=<ID=DP,Number=1,Type=Integer,Description="Total Depth">
##INFO=<ID=GU,Number=.,Type=String,Description="Genotype is Unidentified:R=A/G, Y=T/C">
##FILTER=<ID=q10,Description="Quality below 10">
##FORMAT=<ID=GT,Number=1,Type=String,Description="Genotype">
##FORMAT=<ID=GQ,Number=1,Type=Integer,Description="Genotype Quality">
##FORMAT=<ID=DP,Number=1,Type=Integer,Description="Read Depth">
#CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO    FORMAT  NA00001
chr1    129     .       G       A,R     0       PASS    NS=1:DP=5:GU=A/G        GT:GQ:DP        1/2:0:5
chr2    5894    .       A       G,R     0       PASS    NS=1:DP=9:GU=A/G        GT:GQ:DP        1/2:0:9
chr2    7670    .       A       T,R     0       PASS    NS=1:DP=8:GU=A/G        GT:GQ:DP        1/2:0:8
chr2    9456    .       G       A,R     0       PASS    NS=1:DP=9:GU=A/G        GT:GQ:DP        1/2:0:9
chr3    858     .       A       C       0       PASS    NS=1:DP=13      GT:GQ:DP        1/1:0:13
chr3    1125    .       G       Y       0       PASS    NS=1:DP=11:GU=T/C       GT:GQ:DP        1/1:0:11
chr3    1369    .       G       C       0       PASS    NS=1:DP=12      GT:GQ:DP        0/1:0:12
chr3    2440    .       C       G       0       PASS    NS=1:DP=17      GT:GQ:DP        0/1:0:17
chr3    2504    .       C       T       0       PASS    NS=1:DP=9       GT:GQ:DP        0/1:0:9
chr3    2584    .       G       A,R     0       PASS    NS=1:DP=7:GU=A/G        GT:GQ:DP        1/2:0:7
chr3    2893    .       T       C       0       PASS    NS=1:DP=13      GT:GQ:DP        0/1:0:13
chr3    2939    .       C       T,Y     0       PASS    NS=1:DP=13:GU=T/C       GT:GQ:DP        1/2:0:13
chr3    3065    .       G       A,R     0       PASS    NS=1:DP=5:GU=A/G        GT:GQ:DP        1/2:0:5
chr3    3254    .       T       A,R     0       PASS    NS=1:DP=11:GU=A/G       GT:GQ:DP        1/2:0:11
chr3    3259    .       A       G,R     0       PASS    NS=1:DP=11:GU=A/G       GT:GQ:DP        1/2:0:11
chr3    3283    .       G       A,R     0       PASS    NS=1:DP=11:GU=A/G       GT:GQ:DP        1/2:0:11
chr3    3295    .       C       R       0       PASS    NS=1:DP=7:GU=A/G        GT:GQ:DP        0/1:0:7
chr3    3320    .       A       G,R     0       PASS    NS=1:DP=13:GU=A/G       GT:GQ:DP        1/2:0:13
chr3    3377    .       T       R       0       PASS    NS=1:DP=9:GU=A/G        GT:GQ:DP        0/1:0:9
chr3    3404    .       C       R       0       PASS    NS=1:DP=9:GU=A/G        GT:GQ:DP        0/1:0:9
chr3    3608    .       T       G,Y     0       PASS    NS=1:DP=8:GU=T/C        GT:GQ:DP        1/2:0:8
chr3    5893    .       A       G,R     0       PASS    NS=1:DP=13:GU=A/G       GT:GQ:DP        1/2:0:13
chr3    5926    .       C       T       0       PASS    NS=1:DP=13      GT:GQ:DP        1/1:0:13

I am not sure why would this happen.    Thank you.
Best

**Comment by guoweilong** [comment]
You might need to specific the parameter as following to show all positions, including the non-SNV site.


===============
$ cgmaptools snv -h
....
  -a, --all_nt          Show all sites with enough coverage (-l). Only show
                        SNP sites if not specified.
===============


Best,
Weilong


At 2017-12-21 23:24:23, "3211895" <notifications@github.com> wrote:


@guoweilong Hi,
I am sorry, I means I can still not derive any SNP which genotype is 0/0, including the test dataset. Here is the VCF I derived from the test data:
##fileformat=VCFv4.2
##fileDate=20171221
##source=CGmapTools
##INFO=<ID=NS,Number=1,Type=Integer,Description="Number of Samples With Data">
##INFO=<ID=DP,Number=1,Type=Integer,Description="Total Depth">
##INFO=<ID=GU,Number=.,Type=String,Description="Genotype is Unidentified:R=A/G, Y=T/C">
##FILTER=<ID=q10,Description="Quality below 10">
##FORMAT=<ID=GT,Number=1,Type=String,Description="Genotype">
##FORMAT=<ID=GQ,Number=1,Type=Integer,Description="Genotype Quality">
##FORMAT=<ID=DP,Number=1,Type=Integer,Description="Read Depth">
#CHROM POS ID REF ALT QUAL FILTER INFO FORMAT NA00001
chr1 129 . G A,R 0 PASS NS=1:DP=5:GU=A/G GT:GQ:DP 1/2:0:5
chr2 5894 . A G,R 0 PASS NS=1:DP=9:GU=A/G GT:GQ:DP 1/2:0:9
chr2 7670 . A T,R 0 PASS NS=1:DP=8:GU=A/G GT:GQ:DP 1/2:0:8
chr2 9456 . G A,R 0 PASS NS=1:DP=9:GU=A/G GT:GQ:DP 1/2:0:9
chr3 858 . A C 0 PASS NS=1:DP=13 GT:GQ:DP 1/1:0:13
chr3 1125 . G Y 0 PASS NS=1:DP=11:GU=T/C GT:GQ:DP 1/1:0:11
chr3 1369 . G C 0 PASS NS=1:DP=12 GT:GQ:DP 0/1:0:12
chr3 2440 . C G 0 PASS NS=1:DP=17 GT:GQ:DP 0/1:0:17
chr3 2504 . C T 0 PASS NS=1:DP=9 GT:GQ:DP 0/1:0:9
chr3 2584 . G A,R 0 PASS NS=1:DP=7:GU=A/G GT:GQ:DP 1/2:0:7
chr3 2893 . T C 0 PASS NS=1:DP=13 GT:GQ:DP 0/1:0:13
chr3 2939 . C T,Y 0 PASS NS=1:DP=13:GU=T/C GT:GQ:DP 1/2:0:13
chr3 3065 . G A,R 0 PASS NS=1:DP=5:GU=A/G GT:GQ:DP 1/2:0:5
chr3 3254 . T A,R 0 PASS NS=1:DP=11:GU=A/G GT:GQ:DP 1/2:0:11
chr3 3259 . A G,R 0 PASS NS=1:DP=11:GU=A/G GT:GQ:DP 1/2:0:11
chr3 3283 . G A,R 0 PASS NS=1:DP=11:GU=A/G GT:GQ:DP 1/2:0:11
chr3 3295 . C R 0 PASS NS=1:DP=7:GU=A/G GT:GQ:DP 0/1:0:7
chr3 3320 . A G,R 0 PASS NS=1:DP=13:GU=A/G GT:GQ:DP 1/2:0:13
chr3 3377 . T R 0 PASS NS=1:DP=9:GU=A/G GT:GQ:DP 0/1:0:9
chr3 3404 . C R 0 PASS NS=1:DP=9:GU=A/G GT:GQ:DP 0/1:0:9
chr3 3608 . T G,Y 0 PASS NS=1:DP=8:GU=T/C GT:GQ:DP 1/2:0:8
chr3 5893 . A G,R 0 PASS NS=1:DP=13:GU=A/G GT:GQ:DP 1/2:0:13
chr3 5926 . C T 0 PASS NS=1:DP=13 GT:GQ:DP 1/1:0:13

I am not sure why would this happen. Thank you.
Best
