### ISSUE TITLE
error with mtr

### ISSUE THREAD

**Issue by zhangaicen** [guoweilong/cgmaptools#60]
Hi，Guo,
I tried to use mtr to calculate methylation level in regions, my .bed and .CGmap.gz are all sorted as below: 
![image](https://user-images.githubusercontent.com/67790480/191022793-5e08971f-6e88-4c5d-99d2-06bc4c1c5d37.png)
but after run the mtr command， only Chr1， Chr10， Chr11，Chr12 methylation information level are available, while other chr. are lost, how to solve this problem?

Thank you.

**Comment by guoweilong** [comment]
The program is sensitive with chromosome orders of "string". Thus it would be suggest to use "cgmaptools split" to split file by chromosome, then work on mtr.
Or use "cgmaptools sort" to sort the chr and pos columns before running.
The 1st way is preferred.

Weilong



At 2022-09-19 21:02:18, "zhangaicen" ***@***.***> wrote:

Hi，Guo,
I tried to use mtr to calculate methylation level in regions, my .bed and .CGmap.gz are all sorted as below:

but after run the mtr command， only Chr1， Chr10， Chr11，Chr12 methylation information level are available, while other chr. are lost, how to solve this problem?

Thank you.

**Comment by zhangaicen** [comment]
the cgmaptools sort works, thank you.
