### ISSUE TITLE
Great!

### ISSUE THREAD

**Issue by hmyh1202** [guoweilong/cgmaptools#7]
New Paper comming!
https://www.nature.com/articles/s41588-017-0007-6

**Comment by guoweilong** [comment]
@hmyh1202 Yes.

Let's congrates to @Perry-Zhu on his new paper!

A secret is that some of the analysis and visualization method in Ping Zhu's paper are actually implemented in CGmapTools!

Weilong

**Comment by Perry-Zhu** [comment]
Thanks @hmyh1202 and @guoweilong . 

Weilong helped a lot to analyze bisulfite sequencing data in this project.

**Comment by hmyh1202** [comment]
Yes, in the method of 'SNP calling and parental genome tracing', two independent methods based on the binomial test and Bayesian inference, which may be done by cpmaptools！

**Comment by guoweilong** [comment]
You can read the CGmapTools paper (bioinformatics) for more details about the improvements. The BayesWC method is different from that was implemented in Bis-SNP.
In Ping Zhu's new Nature Genetics paper, he previously used Bis-SNP, and then neglected the C-T mutation sites. While, we proved BayesWC and BinomWC would be more accurate, considering C-T and A-G wildcard.

As you can see, our CGmapTools comes out earlier than Ping's Nature Genetics paper; though they were done in parallel.

Best,
Weilong
