### ISSUE TITLE
CGmapMethInBins  script line 66 have a little mistake

### ISSUE THREAD

**Issue by qliugithub** [guoweilong/cgmaptools#8]
First, It's a good software for DNA methylation analysis. but When I run the command 'cgmaptools mbin -i WG.CGmap.gz -B 500 -c 4 -f png -t WG -p WG > mbin.WG.data' , but display 'File "/public/home/qliu/bio_soft/cgmaptools/bin/CGmapMethInBins", line 66
    print "\n[Error]:\n\t File cannot be open: ", fn' .  I open the script of CGmapMethInBins, find line 66 was 
'print "\n[Error]:\n\t File cannot be open: ", fn'。 but it use in python2 not in python3. finally I fix the conmmand with ''print("\n[Error]:\n\t File cannot be open: ", fn) " ,and then run without mistake report.

**Comment by guoweilong** [comment]
Great thanks for your comments. We have fixed related issue since v0.0.8.

You valuable feedback makes CGmapTools a better software!

Best,
Weilong
