### ISSUE TITLE
Allele-Specific methylated Site calling?

### ISSUE THREAD

**Issue by 3211895** [guoweilong/cgmaptools#9]
Hi WeiLong:
I have a question about the program.
If I remove the code " # next if ( $allele1 eq $allele2 ); # only retain heterozygous SNP site (htSNP)" of ASM.pl, the results will contain the methylation information of homozygous SNP sites. Are the results correct?
Thanks

Best

**Comment by Perry-Zhu** [comment]
Hi @3211895 

Allele specific methylation analysis is primarily to compare the DNA methylation linked by two different alleles (heterozygous genotype). Obviously, it's meaningless to perform ASM on homozygous sites as there is even no two groups of DNA methylation for comparison.

Best,
Ping

**Comment by hmyh1202** [comment]
@Perry-Zhu 
In your NG paper, how to draw the pic below:
![default](https://user-images.githubusercontent.com/18067365/41272726-e7ce9180-6e48-11e8-9342-8e3ec73ebafa.png)
